---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    author: Olusoji
    name: postgres
spec:
 ports:
  - port: 5432
    targetPort: 5432
 selector:
   author: Olusoji
    name: postgres
...


