---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    author: Olusoji
    name: postgres-pod
spec:
  containers:
    - name: postgres-pod
      image: postgres
      env:
       - name: POSTGRES_PASSWORD
         value: Olusoji
       - name: POSTGRES_USER
         value: Olusoji
       - name: POSTGRES_DB
         value: mydb
      ports:
        - containerPort: 5432
...