---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    author: Olusoji
    name: redis
spec:
 ports:
  - port: 6379
    targetPort: 6379
 selector:
   author: Olusoji
   name: redis
...


