---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    author: Olusoji
    name: voting-app-service
spec:
 type: LoadBalancer
 ports:
  - port: 80
    targetPort: 80
 selector:
   author: Olusoji
    name: voting-app-pod
...


